name: pharaoh
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  meta: ^1.11.0
  mime: ^1.0.4
  collection: ^1.18.0
  http_parser: ^4.0.2
  path_to_regexp: ^0.4.0
  mason_logger: ^0.2.10

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
