name: pharaoh_annotations
description: Class and annotation based development with Pharaoh.
version: 0.0.1
repository: https://github.com/codekeyz/pharaoh/tree/main/packages/pharaoh_annotations

environment:
  sdk: ^3.0.0

dependencies:
  pharaoh:
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
