name: pharaoh_basic_auth
description: Simple plug & play HTTP basic auth middleware for Pharaoh.
version: 1.0.0
repository: https://github.com/codekeyz/pharaoh/tree/main/packages/pharaoh_basic_auth

environment:
  sdk: ^3.0.0

dependencies:
  pharaoh: ^0.0.3

dev_dependencies:
  lints: ^3.0.0
  supertest: ^1.0.0
