name: pharaoh_basic_auth
description: Simple plug & play HTTP basic auth middleware for Pharaoh.
version: 1.0.0
repository: https://github.com/codekeyz/pharaoh/tree/main/packages/pharaoh_basic_auth

environment:
  sdk: ^3.0.0

dependencies:
  pharaoh:
    path: ../../

dev_dependencies:
  lints: ^3.0.0
  spookie: ^1.0.1
