name: spanner
description: A crazy fast HTTP router, internally uses an highly performant Radix Tree (aka compact Prefix Tree), supports route params, wildcards.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  pharaoh:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  spookie:
