name: pharaoh_examples
description: A set of examples showing effective use of Pharaoh.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  pharaoh:
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2
  pharaoh_static:
    path: ../packages/pharaoh_static

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  http: ^1.1.0
