name: pharaoh_examples
description: A set of examples showing effective use of Pharaoh.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.5

dependencies:
  pharaoh:
  shelf_cors_headers: 0.1.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
