name: supertest
description: SuperAgent driven library for testing Dart HTTP servers.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.0.0
  test: ^1.24.9

dev_dependencies:
  lints: ^3.0.0
  pharaoh:
