name: supertest
description: SuperAgent driven library for testing Dart HTTP servers.
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  http: ^1.1.0
  test: ^1.21.0

dev_dependencies:
  lints: ^2.0.0
  pharaoh:
