name: pha_swagger
description: Automatically generate swagger docs for Pharaoh
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

dependencies:
  pharaoh:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
