name: examples
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  pharaoh:
    path: ../
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
