name: spookie
description: SuperAgent driven library for testing Dart HTTP servers.
version: 1.0.2+3
repository: https://github.com/codekeyz/pharaoh/tree/main/packages/spookie

environment:
  sdk: ^3.0.0

dependencies:
  http: any
  test: any

dev_dependencies:
  pharaoh:
