name: pharaoh
description: Minimalist web-server library for Dart
version: 0.0.8+1
repository: https://github.com/codekeyz/pharaoh/tree/main/packages/pharaoh

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.15.0
  spanner: ^1.0.4
  mime: ^1.0.4
  collection: ^1.18.0
  http_parser: ^4.0.2
  crypto: ^3.0.3
  uuid: ^4.2.1

  # We only need this to implement inter-operability for shelf
  shelf: ^1.4.1

  # framework
  reflectable: ^4.0.12
  get_it: ^8.0.2
  grammer: ^1.0.3
  dotenv: ^4.2.0
  ez_validator_dart: ^0.3.1
  spookie: ^1.0.2+3

dev_dependencies:
  lints: ^3.0.0
