name: pharaoh
description: Fast, unopinionated, minimalist web framework for Dart. Heavily inspired by ExpressJS
version: 0.0.6+2
repository: https://github.com/codekeyz/pharaoh/tree/main/packages/pharaoh

environment:
  sdk: ^3.0.0

dependencies:
  meta:
  spanner: ^1.0.1+3
  mime: ^1.0.4
  collection: ^1.18.0
  http_parser: ^4.0.2
  crypto: ^3.0.3
  uuid: ^4.2.1

  # We only need this to implement inter-operability for shelf
  shelf: ^1.4.1

dev_dependencies:
  spookie:
  lints: ^3.0.0
