name: pharaoh
description: Minimalist web-server library for Dart
version: 0.0.6+2
repository: https://github.com/codekeyz/pharaoh/tree/main/packages/pharaoh

environment:
  sdk: ^3.0.0

dependencies:
  meta:
  spanner: ^1.0.1+3
  mime: ^1.0.4
  collection: ^1.18.0
  http_parser: ^4.0.2
  crypto: ^3.0.3
  uuid: ^4.2.1

  # We only need this to implement inter-operability for shelf
  shelf: ^1.4.1

  # framework
  reflectable: 4.0.6
  get_it: ^7.6.7
  grammer: ^1.0.3
  dotenv: ^4.2.0
  ez_validator:
    # ignore: invalid_dependency
    git: https://github.com/codekeyz/ez-validator-yaroo.git
  spookie:

dev_dependencies:
  lints: ^3.0.0

dependency_overrides:
  analyzer: 6.4.0
