name: pharaoh_jwt_auth
description: Pharaoh middleware that validates a JsonWebToken (JWT) and set the req.auth with the attributes
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  pharaoh: ^0.0.4
  dart_jsonwebtoken: ^2.12.1

dev_dependencies:
  lints: ^3.0.0
  spookie: ^1.0.1
